name: Unit tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Configure tests
        run: >-
          cmake -S . -B build
          -DCMAKE_CXX_COMPILER=clang++
          -DCMAKE_CXX_STANDARD=11
          -DCMAKE_CXX_STANDARD_REQUIRED=ON
          -DCMAKE_CXX_EXTENSIONS=OFF
          -DCMAKE_POLICY_VERSION_MINIMUM=3.5
          -DBUILD_TESTING=ON
          -DRATIONAL_NUMBER_BUILD_EXAMPLE=OFF
      - name: Build tests
        run: cmake --build build --target rational_number_tests --parallel 2
      - name: Run unit tests
        run: ctest --test-dir build --output-on-failure
